### ISSUE TITLE
Documentation for using moment

### ISSUE THREAD

**Issue by macx** [helpers/handlebars-helpers#304] opened 2018-01-23 09:51 UTC
I'm always struggling using moment parameters in Handlebars because of the poor documentation. To support moment, you've used [helpers/helper-date](https://github.com/helpers/helper-date), which also has a lack of a documention. The only thing I could do is this:

```
{{moment date "MM:mm"}
```
But I can't use moment params like this:

```
{{moment date add=daysadd format="dddd"}}
{{moment date startOf="month" format="dddd, DD MMMM YYYY HH:mm:ss ZZ"}}
```

Two questions:

* What do you think to implement [helpers/helper-moment](https://github.com/helpers/helper-moment) instead? This has a really good doc how to use the parameters in Handlebars.
* Is it possible to override moment with helper-moment by myself?

**Comment by doowb** [comment] 2018-01-23 17:34
> Is it possible to override moment with helper-moment by myself

You can register `helper-moment` directly with handlebars after registering `handlebars-helpers`:

```js
Handlebars.registerHelper('moment', require('helper-moment'));
```

>  has a lack of a documention

There is documentation on usage [here](https://github.com/helpers/helper-date#usage) but if you feel it's lacking, PR's are welcome.

> What do you think to implement helpers/helper-moment instead?

We might consider this, but there might need to be other changes necessary since [helper-date](https://github.com/helpers/helper-date) also uses date.js to allow taking a human readable date phrase before formatting.

I'm going to close this. If you run into any issues with usage, please feel free to open an issue with a minimum reproducable use case to try to get it fixed.

**Closed by doowb** 2018-01-23 17:34 UTC
