### ISSUE TITLE
How To : Use handlebars-helpers with webpack & typescript

### ISSUE THREAD

**Issue by spplante** [helpers/handlebars-helpers#263] opened 2017-04-24 16:47 UTC
Hi there,

I was wondering if there is any way to bundle handlebars-helpers with my webpack project which uses TypeScript. I can't use any handlebars loader because the template needs to be evaluated client side. Handlebars is already bundled by WebPack and it works great, but I can't figure out how to tell WebPack how to use a node.js module like handlebars-helpers...

I tried doing the following :

```node
import * as Handlebars from "handlebars";
var helpers = require('handlebars-helpers')({
  handlebars: Handlebars
});
```

But I had some errors with WebPack not being able to resolve "fs", so I added the following configuration :

```json
node: {
        fs: 'empty'
    },
```

It's already better but now I have all kinds of warnings like the following: 

```node
WARNING in ./~/handlebars-helpers/lib/utils/utils.js
Critical dependencies:
3:34-41 require function is used in a way in which dependencies cannot be statically extracted
 @ ./~/handlebars-helpers/lib/utils/utils.js 3:34-41

WARNING in ./~/is-descriptor/utils.js
Critical dependencies:
7:34-41 require function is used in a way in which dependencies cannot be statically extracted
 @ ./~/is-descriptor/utils.js 7:34-41
```

Anyone ever used handlebars-helpers with WebPack? I would really appreciate any help :)

Thanks!

**Comment by doowb** [comment] 2017-04-24 17:30
Hi @spplante, this is a duplicate of #261.

**Closed by doowb** 2017-04-24 17:30 UTC

**Comment by spplante** [comment] 2017-04-24 18:35
@dowwb You make my day, it works perfectly thank you so much!

**Comment by flyingL123** [comment] 2018-07-30 20:28
@spplante can you show the code that ultimately got this working? I'm struggling with the same problem.

**Comment by spplante** [comment] 2018-07-31 00:51
Just realized I answered in the wrong thread...Here is the answer I posted: 

@deboyblog it's kinda hard to share my webpack config because I used this in a Microsoft project which let's you update the base webpack.config file through their own API, but here's what the gulp file looks like :

```node
const gulp = require('gulp');
const build = require('@microsoft/sp-build-web');

/********************************************************************************************
 * Adds an alias for handlebars in order to avoid errors while gulping the project
 * https://github.com/wycats/handlebars.js/issues/1174
 * Adds a loader and a node setting for webpacking the handlebars-helpers correctly
 * https://github.com/helpers/handlebars-helpers/issues/263
 ********************************************************************************************/
build.configureWebpack.mergeConfig({
  additionalConfiguration: (generatedConfiguration) => {

    generatedConfiguration.resolve.alias = { handlebars: 'handlebars/dist/handlebars.min.js' };

    generatedConfiguration.module.rules.push(
      { test: /\.js$/, loader: 'unlazy-loader' }
    );

    generatedConfiguration.node = {
      fs: 'empty'
    }
    
    return generatedConfiguration;
  }
});

build.initialize(gulp);
```

Basically, in your **webpack.config** file, you need those 3 things :

- An **alias** as specified above
- A **rule** (webpack 2) or **loader** (webpack 1) as specified above
- A **node** settings which as specified above

In a typical **webpack.config** file, it should look something like this :

```node
module.exports = {
    ...
    resolve: {
        alias: {
           handlebars: 'handlebars/dist/handlebars.min.js'
        }
    }
    ...
    module: {
        ...
        rules: [
            { test: /\.js$/, loader: 'unlazy-loader' }
        ]
    }
    node: {
        fs: 'empty'
    }
}
```

**Comment by flyingL123** [comment] 2018-07-31 01:10
Thanks for your help @spplante. I was able to get rid of the `fs` error following your example. I then got the same type of error for `readstring`, so I added that to the config as well, and that error went away. However, now when the page loads, I get an error from line 47 of `node_modules/ansi-colors/index.js`:

`Uncaught TypeError: require is not a function`

Any idea what is causing that?

**Comment by spplante** [comment] 2018-07-31 03:15
Not sure I can help at this point, the message kinda looks like the message I got rid of by using lazy-loader, maybe you are missing something in your config? Do you have .js in the extensions part of the config?

**Comment by flyingL123** [comment] 2018-07-31 14:39
Argh, this is so frustrating. This is my webpack config. I'm using unlazy-loader just like you are in your example:

```
var CleanWebpackPlugin = require('clean-webpack-plugin'),
    config = require('./config.json'),
    LodashModuleReplacementPlugin = require('lodash-webpack-plugin'),
    path = require('path'),
    webpack = require('webpack');

module.exports = {
    bail: true,
    context: __dirname,
    devtool: 'source-map',
    entry: {
        main: './assets/js/app.js',
    },
    module: {
        rules: [
            {
                test: /\.js$/,
                loader: 'unlazy-loader',
            },
            {
                test: /\.js$/,
                include: /(assets\/js|assets\\js|node_modules\/@bigcommerce\/stencil-utils|node_modules\\@bigcommerce\\stencil-utils|node_modules\/foundation-sites\/js|node_modules\\foundation-sites\\js)/,
                use: {
                    loader: 'babel-loader',
                    options: {
                        cacheDirectory: true,
                        compact: true,
                        minified: true,
                        plugins: [
                            'dynamic-import-webpack', // Needed for dynamic imports.
                            'lodash', // Automagically tree-shakes lodash.
                            'transform-regenerator', // Transforms async and generator functions.
                        ],
                        presets: [
                            ['env', {
                                loose: true, // Enable "loose" transformations for any plugins in this preset that allow them.
                                modules: false, // Don't transform modules; needed for tree-shaking.
                                useBuiltIns: true, // Tree-shake babel-polyfill.
                            }],
                        ],
                    }
                }
            },
        ],
    },
    output: {
        chunkFilename: 'theme-bundle.chunk.[name].js',
        filename: 'theme-bundle.[name].js',
        path: path.resolve(__dirname, "assets/dist"),
    },
    plugins: [
        new CleanWebpackPlugin(['assets/dist'], {
            verbose: true,
            watch: false,
        }),
        new webpack.LoaderOptionsPlugin({
             minimize: true,
        }),
        new LodashModuleReplacementPlugin, // Complements 'babel-plugin-lodash by shrinking it's cherry-picked builds further.
        new webpack.ProvidePlugin({
            $: 'jquery',
            jQuery: 'jquery',
            'window.jQuery': 'jquery',
        }),
        new webpack.optimize.CommonsChunkPlugin({
            children: true,
            minChunks: 2,
        }),
    ],
    resolve: {
        alias: {
            jquery: path.resolve(__dirname, 'node_modules/jquery/dist/jquery.min.js'),
            jstree: path.resolve(__dirname, 'node_modules/jstree/dist/jstree.min.js'),
            handlebars: path.resolve(__dirname, 'node_modules/handlebars/dist/handlebars.runtime.min.js'),
        },
    },
    watch: false,
    node: {
        fs: 'empty',
        readline: 'empty'
    }
};
```

**Comment by flyingL123** [comment] 2018-07-31 19:10
@spplante I just updated to webpack 4 and the issue goes away. Don't need to use unlazy-loader at all. Question though...did you find that adding handlebars-helpers to the project greatly increased the bundle size?

My main bundle output went from 4.2 to 8.5 MB simply by adding a single line to import `handlebars-helpers`.

**Comment by spplante** [comment] 2018-07-31 20:16
Hmm didn’t notice the package size, there must be quite a lot of code since there is 180+ extensions in there, some of them requiring their own dependencies such as the « moment » helper (momentJS)
