### ISSUE TITLE
Helper within each

### ISSUE THREAD

**Issue by jinky32** [helpers/handlebars-helpers#309] opened 2018-02-03 20:09 UTC
Hi,

I have looked at #308 but I'm not sure that it will allow me to do what I would like.

I have a small Express app with a Controller that passes two arrays to a view
`res.render('story', {taggedWords: taggedWords, storyArray:storyArray});`

`storyArray` looks like  `[ 'I', 'am', 'using', 'helpers']`

`taggedWords` looks like `[[ 'using', 'verb' ],[ 'helpers', 'Noun' ]]`

I am trying to print out some markup if a value in `taggedWords` appears in `storyArray`

```handlebars
{{#each taggedWords as |item|}}
  {{#contains storyArray item.[0]}}
    <p>WOOT</p>
    <span class="{{item.[1]}}">{{item.[0]}}</span>
  {{/contains}}
  {{else}}
    This will be rendered.
{{/each}}
```

Running

```handlebars
{{#each taggedWords as |item|}}
  <p>WOOT</p>
  <span class="{{item.[1]}}">{{item.[0]}}</span>
{{/each}}
```

 works as expected, as does 

```handlebars
{{#contains storyArray 'helpers'}}
  <p>WOOT</p>
{{/contains}}
{{else}}
  This will be rendered.
```

but they don't seem to work in combination.  I don't get an error message, it's just that nothing get rendered.

**Comment by doowb** [comment] 2018-02-03 20:28
I think your `{{else}}` is in the wrong place. It should be above the `{{/contains}}`

**Comment by jinky32** [comment] 2018-02-03 20:52
Many thanks for the quick reply.  That does improve things (i.e. it returns false and `This will be rendered.` is rendered).  
I think however that `{{#contains storyArray item.[0]}}` should be true and does work as expected if I just have 
`{{#contains storyArray 'helpers'}}`
`<p>WOOT</p>`
`{{/contains}}`
e.g. it's not wrapped within the `{{#each}}`

**Comment by doowb** [comment] 2018-05-25 15:59
@jinky32 I just saw your last comment on this. I think the issue is that you'll need to use the parent syntax to access the `storyArray` from inside the `{{#each}}` block:

```handlebars
{{#each taggedWords as |item|}}
  {{#contains ../storyArray item.[0]}}
    <p>WOOT</p>
    <span class="{{item.[1]}}">{{item.[0]}}</span>
  {{else}}
    This will be rendered.
  {{/contains}}
{{/each}}
```

You can find more information about [handlebars paths here](http://handlebarsjs.com/#paths). I'm going to close this since I think it's about handlebars syntax and not a bug with a helper from this library.

**Closed by doowb** 2018-05-25 15:59 UTC
