### ISSUE TITLE
#is helper is adding the value 'false' to generated pages

### ISSUE THREAD

**Issue by myorangeca** [helpers/handlebars-helpers#287] opened 2017-08-30 08:51 UTC
I have the following is helper:

{{#is pagename "===" "intel_introduction"}}class="active"{{/is}}

For false value its actually adding the text "false" in the generated html pages. 

```
var rename = require('gulp-rename');
var assemble = require('assemble');
var helpers = require('handlebars-helpers');
var app = assemble();
var prettify = require('gulp-prettify');
var config = require('../config');
//var isHelper = require(config.paths.path_src + 'templates/helpers/ishelper');
 
gulp.task('init', function(cb) {
  //app.helper(config.paths.path_src + 'partials/_helpers/*.js');
  //app.helper(config.paths.path_src + 'templates/helpers/ishelper.js');
  app.helper('is', helpers.is);
  //app.helper('contains', helpers.comparison());
  app.partials(config.paths.path_src + 'templates/includes/**/*.hbs');
  app.layouts(config.paths.path_src + 'templates/layouts/**/*.hbs');
  app.pages(config.paths.path_src + 'templates/content/**/*.hbs');
  cb();
});
 
gulp.task('assemble', ['init'], function() {
  return app.toStream('pages')
    .pipe(app.renderFile())
    .pipe(prettify({
        indent_inner_html: false,
        preserve_newlines: true,
        end_with_newline: true,
        extra_liners: ['head', 'body']
    }))
    .pipe(rename({
        extname: '.html'
    }))
    .pipe(rename({dirname: ''}))
    .pipe(app.dest('site'));
});
 
gulp.task('test', ['assemble']);
```

**Comment by doowb** [comment] 2017-08-30 14:52
@myorangeca please simplify your code down to the minimum that is necessary to reproduce the issue.

From looking at this, you're using the `is` helper incorrectly. See [the usage docs](https://github.com/helpers/handlebars-helpers#usage) for how to get the helpers you need and the [{{is}} helper docs](https://github.com/helpers/handlebars-helpers#is) for how to use the helper in a template.

**Comment by myorangeca** [comment] 2017-08-30 18:31
Hi @doowb 

I am really a newbie at this, the documentation looks unclear to me. Would love to see an example of how it works or suppose to work. Not sure if I missed any example codes from the documentation.

**Comment by doowb** [comment] 2017-08-30 19:18
> I am really a newbie at this

Everyone starts somewhere :) I know from our perspective it can be hard to know what needs explaining and what is assumed to be known. I hope the following example helps.

This example is using the `is` helper from `handlebars-helpers` with `assemble`:

**assemblefile.js**

```js
var assemble = require('assemble');
var helpers = require('handlebars-helpers');
var app = assemble();

app.task('init', function(cb) {
  /**
   * Get the `is` helper directly from the `comparison` collection.
   */

  var isHelper = helpers.comparison().is;

  /**
   * Register the `is` helper with assemble so that it can be used.
   */

  app.helper('is', isHelper);

  app.partials('src/templates/includes/**/*.hbs');
  app.layouts('src/templates/layouts/**/*.hbs');
  app.pages('src/templates/content/**/*.hbs');

  // add data to use in the example
  app.data({A: 'foo', B: 'foo'});
  cb();
});

app.task('assemble', ['init'], function() {
  return app.toStream('pages')
    .pipe(app.renderFile())
    .pipe(app.dest('site'));
});

app.task('default', ['assemble']);

module.exports = app;
```

**src/templates/content/index.hbs**

```handlebars
{{#is A B}}
  A is equal to B
{{else}}
  A is not equal to B
{{/is}}
```

You can run `assemble` from the command line to run the `default` task in the `assemblefile.js` that will run the code and you'll see this in:

**site/index.hbs**

```html
  A is equal to B
```

I removed all of the extra code and I'm using `assemble` directly to remove the dependency on `gulp` just to show the simple use case.

**Comment by doowb** [comment] 2018-01-26 21:00
Since this doesn't look like a bug, I'm going to close it. For non-issue related questions, try asking on StackOverflow.

**Closed by doowb** 2018-01-26 21:00 UTC
